name: CNAF
on: push

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Call the CNAF route
        run: 'curl --fail --silent -H "X-Api-Key: ${{ secrets.API_KEY }}" "https://particulier.api.gouv.fr/api/v2/composition-familiale?numeroAllocataire=${{ secrets.NUMERO_ALLOCATAIRE }}&codePostal=${{ secrets.CODE_POSTAL }}"'
