name: DGFIP
on:
  schedule:
    - cron:  '0/5 * * * *'

jobs:
  ping:
    runs-on: self-hosted
    steps:
      - name: Call the DGFIP route
        run: 'curl --fail --silent -H "X-Api-Key: ${{ secrets.API_KEY }}" "https://particulier.api.gouv.fr/api/v2/avis-imposition?referenceAvis=lol${{ secrets.REFERENCE_AVIS }}&numeroFiscal=${{ secrets.NUMERO_FISCAL }}"'
      - name: Create the Mattermost failure message
        if: ${{ failure() }}
        run: |
          echo "{\"text\":\"<!channel>**DGFIP endpoints ping failed! :rotating_light:**\",\"username\":\"API Particulier monitoring\",\"icon_url\":\"https://upload.wikimedia.org/wikipedia/fr/thumb/6/6d/Logo_DGFP-fr.svg/1200px-Logo_DGFP-fr.svg.png\"}" > mattermost.json
      - uses: mattermost/action-mattermost-notify@master
        if: ${{ failure() }}
        env:
          MATTERMOST_WEBHOOK_URL: ${{ secrets.MATTERMOST_WEBHOOK_URL }}
