name: DGFIP
on: push

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Call the DGFIP route
        run: 'curl --fail --silent -H "X-Api-Key: ${{ secrets.API_KEY }}" "https://particulier.api.gouv.fr/api/v2/avis-imposition?referenceAvis=${{ secrets.REFERENCE_AVIS }}&numeroFiscal=${{ secrets.NUMERO_FISCAL }}"'
