name: DGFIP
on:
  workflow_dispatch

jobs:
  ping:
    runs-on: self-hosted
    steps:
      - name: Call the DGFIP route
        run: 'curl --fail --silent -H "X-Api-Key: ${{ secrets.API_KEY }}" "https://particulier.api.gouv.fr/api/v2/avis-imposition?referenceAvis=${{ secrets.REFERENCE_AVIS }}&numeroFiscal=${{ secrets.NUMERO_FISCAL }}"'
      - name: Create the Mattermost failure message
        if: ${{ failure() }}
        run: |
          echo "{\"text\":\"**DGFIP endpoints ping failed! :rotating_light:**\",\"username\":\"API Particulier monitoring\"}" > mattermost.json
      - uses: mattermost/action-mattermost-notify@master
        if: ${{ failure() }}
        env:
          MATTERMOST_WEBHOOK_URL: ${{ secrets.MATTERMOST_WEBHOOK_URL }}
      - name: Create the Mattermost failure message
        if: ${{ failure() }}
        run: |
          echo "{\"text\":\"**DGFIP endpoints ping failed! :rotating_light:**\",\"username\":\"API Particulier monitoring\",\"channel\":\"@stan\"}" > mattermost.json
      - uses: mattermost/action-mattermost-notify@master
        if: ${{ failure() }}
        env:
          MATTERMOST_WEBHOOK_URL: ${{ secrets.MATTERMOST_WEBHOOK_URL }}
