name: Global
on:
  workflow_dispatch

jobs:
  ping:
    runs-on: self-hosted
    steps:
      - name: Call the API ping URL
        run: curl --fail --silent https://particulier.api.gouv.fr/api/ping
      - name: Create the Mattermost failure message
        if: ${{ failure() }}
        run: |
          echo "{\"text\":\"**API Particulier ping failed! :rotating_light:**\",\"username\":\"API Particulier monitoring\"}" > mattermost.json
      - uses: mattermost/action-mattermost-notify@master
        if: ${{ failure() }}
        env:
          MATTERMOST_WEBHOOK_URL: ${{ secrets.MATTERMOST_WEBHOOK_URL }}
      - name: Create the Mattermost failure message
        if: ${{ failure() }}
        run: |
          echo "{\"text\":\"**API Particulier ping failed! :rotating_light:**\",\"username\":\"API Particulier monitoring\",\"channel\":\"@stan\"}" > mattermost.json
      - uses: mattermost/action-mattermost-notify@master
        if: ${{ failure() }}
        env:
          MATTERMOST_WEBHOOK_URL: ${{ secrets.MATTERMOST_WEBHOOK_URL }}
