name: Global
on:
  schedule:
    - cron:  '0/5 * * * *'

jobs:
  ping:
    runs-on: self-hosted
    steps:
      - name: Call the API ping URL
        run: curl --fail --silent https://particulier.api.gouv.fr/api/ping
